services:
  rest-api:
    container_name: rest-api-staging
    image: devroadr/cdci_rust:staging
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:8080"
